from .average_pooling1d import get_backward_AveragePooling1D
from .average_pooling2d import get_backward_AveragePooling2D
from .average_pooling3d import get_backward_AveragePooling3D
from .global_average_pooling3d import get_backward_GlobalAveragePooling3D
from .global_average_pooling2d import get_backward_GlobalAveragePooling2D
from .global_average_pooling1d import get_backward_GlobalAveragePooling1D
from .max_pooling2d import get_backward_MaxPooling2D
