from .conv1d import BackwardConv1D, get_backward_Conv1D
from .conv2d import BackwardConv2D, get_backward_Conv2D
from .conv3d import BackwardConv3D, get_backward_Conv3D
from .depthwise_conv1d import BackwardDepthwiseConv1D, get_backward_DepthwiseConv1D
from .depthwise_conv2d import BackwardDepthwiseConv2D, get_backward_DepthwiseConv2D
from .separable_conv1d import BackwardSeparableConv1D, get_backward_SeparableConv1D
from .separable_conv2d import BackwardSeparableConv2D, get_backward_SeparableConv2D
